version: '3'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
      
  
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'  

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
      


  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGDATABASE=db
    ports: 
      - '5050:5050'


  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
       - /usr/app/node_modules
       - ./client:/usr/app
    ports:
       - '3000:3000'

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
