version: '3'

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - '5432:5432'  

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - PGDATABASE=db
    ports: 
      - '5050:5050'