version: '3'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /usr/app/node_modules
      - .:/usr/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379